"""unique name in CharityProject

Revision ID: 43fa71a57d4e
Revises: 37222f0010d8
Create Date: 2024-06-11 15:02:33.442115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fa71a57d4e'
down_revision: Union[str, None] = '37222f0010d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'charityproject', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charityproject', type_='unique')
    # ### end Alembic commands ###
